/*
 * <GL/gl.h> for the Windows (MinGW-w64) build: the real header; on 32-bit
 * Windows with the gl* entry points declared cdecl instead of __stdcall.
 *
 * UNIX OpenGL code assumes a single calling convention. It stores gl* in
 * plain function pointers and calls them later (Open Inventor's
 * SoVertexProperty keeps glVertex3fv in a `void (*)(const char *)`), and
 * hands them to GLU as callbacks. With opengl32.dll's __stdcall entry points
 * that unbalances the stack on Win32. Declared cdecl, those calls resolve to
 * the cdecl wrappers generated by scripts/gen-gl-cdecl.py
 * (libopengl32-cdecl.a), each calling the real __stdcall function.
 *
 * Mesa's gl.h makes its entry points cdecl only for Windows CE; that switch
 * is set just for the inclusion. GLU stays __stdcall (glu32.dll): see
 * <GL/glu.h> next to this file. Defining LIBX11_COMPAT_GL_STDCALL before the
 * inclusion keeps the native declarations (the generated wrappers use it).
 * 64-bit Windows has one calling convention, so there this is the real header.
 */
#ifndef LIBX11_COMPAT_WIN32_GL_GL_H
#define LIBX11_COMPAT_WIN32_GL_GL_H

#if defined(_WIN32) && defined(__i386__) && \
    !defined(LIBX11_COMPAT_GL_STDCALL) && !defined(_WIN32_WCE)
#define _WIN32_WCE 1
#include_next <GL/gl.h>
#undef _WIN32_WCE
#else
#include_next <GL/gl.h>
#endif

#endif /* LIBX11_COMPAT_WIN32_GL_GL_H */
