#!/usr/bin/env python3
"""Generate cdecl OpenGL entry points over opengl32.dll (32-bit Windows).

On Win32, opengl32.dll's gl* functions are __stdcall. UNIX OpenGL code
assumes the platform's single calling convention: it stores gl* in plain
function pointers (Open Inventor's SoVertexProperty keeps glVertex3fv and
friends in `void (*)(const char *)`) and calls them later, which with
__stdcall callees unbalances the stack. compat/win32/include/GL/gl.h
therefore declares gl* as cdecl on Win32, and this script emits a C file
that defines those cdecl symbols, each calling the real __stdcall entry
point (a distinct, @N-decorated symbol in libopengl32.a).

Only functions opengl32.dll exports are generated (they are the only ones
a Win32 program can link directly; later GL comes through
wglGetProcAddress and keeps APIENTRY).

Usage: gen-gl-cdecl.py <gl.h> <opengl32 nm output> > gl-cdecl.c
"""

import re
import sys


def exported_names(nm_path):
    names = set()
    with open(nm_path) as nm:
        for line in nm:
            m = re.search(r" T _(gl[A-Za-z0-9_]+)@\d+$", line.rstrip())
            if m:
                names.add(m.group(1))
    return names


def prototypes(header_path):
    text = open(header_path).read()
    text = re.sub(r"/\*.*?\*/", " ", text, flags=re.S)
    pattern = re.compile(
        r"GLAPI\s+(?P<ret>[^;]*?)\s*GLAPIENTRY\s+(?P<name>gl\w+)\s*"
        r"\((?P<params>[^;]*?)\)\s*;",
        re.S,
    )
    for m in pattern.finditer(text):
        ret = " ".join(m.group("ret").split())
        params = " ".join(m.group("params").split())
        yield m.group("name"), ret, params


def param_names(params):
    if params in ("", "void"):
        return []
    names = []
    for param in params.split(","):
        m = re.search(r"([A-Za-z_]\w*)\s*(\[[^\]]*\])?\s*$", param.strip())
        if not m:
            raise ValueError(f"cannot name parameter {param!r}")
        names.append(m.group(1))
    return names


def main():
    header, nm_path = sys.argv[1], sys.argv[2]
    exported = exported_names(nm_path)
    out = sys.stdout
    out.write(
        "/* Generated by scripts/gen-gl-cdecl.py; do not edit. */\n"
        "#include <GL/gl.h>\n\n"
    )
    seen = set()
    for name, ret, params in prototypes(header):
        if name not in exported or name in seen:
            continue
        seen.add(name)
        args = ", ".join(param_names(params))
        body = ("return " if ret != "void" else "") + f"{name}({args});"
        out.write(
            f"{ret} x11compatCdecl_{name}({params or 'void'});\n"
            f"{ret} x11compatCdecl_{name}({params or 'void'})\n"
            f"{{\n    {body}\n}}\n"
            f'__asm__(".globl _{name}\\n\\t.set _{name}, '
            f'_x11compatCdecl_{name}");\n\n'
        )
    if len(seen) < 300:
        sys.exit(
            f"gen-gl-cdecl: only {len(seen)} functions matched; "
            "gl.h or nm output format changed?"
        )


if __name__ == "__main__":
    main()
